apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: nexus
  namespace: nexus
targetNamespaces:
  - nexus
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/nxrm-operator-certified.nexus: ""
  name: nxrm-operator-certified
  namespace: nexus
spec:
  channel: stable
  installPlanApproval: Automatic
  name: nxrm-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace